//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Order()
        {
            this.tb_ChiTietOrder = new HashSet<tb_ChiTietOrder>();
            this.tb_TichDiem = new HashSet<tb_TichDiem>();
        }
    
        public int MaDonHang { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaPhuongThucThanhToan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsThanhToan { get; set; }
        public Nullable<bool> IsHoanThanh { get; set; }
        public Nullable<bool> IsHuyDon { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<int> MaDiscount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietOrder> tb_ChiTietOrder { get; set; }
        public virtual tb_Customer tb_Customer { get; set; }
        public virtual tb_DiscountCode tb_DiscountCode { get; set; }
        public virtual tb_PhuongThucThanhToan tb_PhuongThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TichDiem> tb_TichDiem { get; set; }
    }
}
