//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQuanLyBanDoCongNgheEntities : DbContext
    {
        public DBQuanLyBanDoCongNgheEntities()
            : base("name=DBQuanLyBanDoCongNgheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_Brand> tb_Brand { get; set; }
        public virtual DbSet<tb_Category> tb_Category { get; set; }
        public virtual DbSet<tb_ChiTietOrder> tb_ChiTietOrder { get; set; }
        public virtual DbSet<tb_ChiTietOrder_Traveler> tb_ChiTietOrder_Traveler { get; set; }
        public virtual DbSet<tb_ChucNang> tb_ChucNang { get; set; }
        public virtual DbSet<tb_Color> tb_Color { get; set; }
        public virtual DbSet<tb_Customer> tb_Customer { get; set; }
        public virtual DbSet<tb_DiscountCode> tb_DiscountCode { get; set; }
        public virtual DbSet<tb_Memory> tb_Memory { get; set; }
        public virtual DbSet<tb_NhanVien> tb_NhanVien { get; set; }
        public virtual DbSet<tb_Order> tb_Order { get; set; }
        public virtual DbSet<tb_PhanQuyen> tb_PhanQuyen { get; set; }
        public virtual DbSet<tb_PhuongThucThanhToan> tb_PhuongThucThanhToan { get; set; }
        public virtual DbSet<tb_Product> tb_Product { get; set; }
        public virtual DbSet<tb_ProductCategory> tb_ProductCategory { get; set; }
        public virtual DbSet<tb_ProductImages> tb_ProductImages { get; set; }
        public virtual DbSet<tb_TaiKhoanNganHang> tb_TaiKhoanNganHang { get; set; }
        public virtual DbSet<tb_TichDiem> tb_TichDiem { get; set; }
        public virtual DbSet<tb_Traveler> tb_Traveler { get; set; }
    }
}
