//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TichDiem
    {
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> SoDiemCongGanNhat { get; set; }
        public Nullable<int> TongSoDiem { get; set; }
        public int MaDonHang { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tb_Customer tb_Customer { get; set; }
        public virtual tb_Order tb_Order { get; set; }
    }
}
